project_id = "ljavuiafiqidnvqsvntl"

[functions.ai-tutor]
verify_jwt = false

[functions.generate-activity]
verify_jwt = false

[functions.teacher-nick]
verify_jwt = false

[functions.quantum-x]
verify_jwt = false

[functions.teacher-samuk]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.generate-study-material]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.generate-boss-questions]
verify_jwt = false

